<?xml version="1.0"?>
<package format="3">
  <name>go2_twist_bridge_py</name>
  <version>0.0.0</version>
  <description>Twist to Go2 Request bridge for the tutorial.</description>
  <maintainer email="student@example.com">student</maintainer>
  <license>Apache-2.0</license>

  <depend>geometry_msgs</depend>
  <depend>rclpy</depend>
  <depend>unitree_api</depend>

  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
